### ISSUE TITLE
Document changes to `init`?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nodenv/nodenv-package-rehash#11]
So, at least for `zsh`, the `nodenv init -` output includes a rehash on every shell initialization:

    command nodenv rehash 2>/dev/null

This is a substantial startup cost, and if I understand nodenv's rehashing correctly, is no longer necessary after installing this plugin?

If that's indeed the case, then a comment in the README about manually copying the `init` code into the README, and removing that line, might be apt. (Of course, this is a non-starter if #8 is actually coming to pass!)

**Comment by ELLIOTTCABLE** [comment]
(Just a hit-and-run note that `nodenv.plugin.zsh` uses `nodenv init --rehash -`, which clears this up!)

**Comment by jasonkarns** [comment]
Did you mean `nodenv init --no-rehash -` ?

**Comment by jasonkarns** [comment]
@ELLIOTTCABLE what do you think of #19 ?
