### ISSUE TITLE
Include this behavior into nodenv core

### ISSUE THREAD

**Issue by therealparmesh** [nodenv/nodenv-package-rehash#13]
It appears that [the inspiration for this plugin] (https://github.com/rbenv/rbenv-gem-rehash) has been deprecated in favor of implementing it as default behavior.

I'm not so sure this is actually working at the moment, so this may be a good opportunity to merge into the `nodenv` core.

I'm curious as to what you think about this idea. Thank you!

**Comment by jasonkarns** [comment]
dupe of #8
