### ISSUE TITLE
This doesn't seem to work when using yarn

### ISSUE THREAD

**Issue by deiga** [nodenv/nodenv-package-rehash#9]
IMO running `yarn global add <foo>` will not automatically rehash. I need to manually run `nodenv rehash` to get access to my new global binary.

**Comment by deiga** [comment]
nvm, this seems to be a PEBKAC. The `brew` installation doesn't run the hooks or even tells me to do it...

**Comment by jasonkarns** [comment]
You have yarn installed via homebrew or the node you're presently running under is installed via homebrew? (reopening to investigate a bit more)
